### ISSUE TITLE
Diseño de diagramas de Flujo

### ISSUE THREAD

**Issue by gibrantpn** [JPacho/ProyectoIntegrador#10]

**Comment by JPacho** [comment]
[Proyecto Integrador.pdf](https://github.com/JPacho/ProyectoIntegrador/files/3668013/Proyecto.Integrador.pdf)

Realicé el diseño del diagrama de flujo con los tres hilos propuestos, podrían verificarlo y decirme si están de acuerdo?

**Comment by JPacho** [comment]
El desarrollo de software se está basando en el diseño de este diagrama de flujo.
