### ISSUE TITLE
Lectura de Sensor de Velocidad

### ISSUE THREAD

**Issue by gibrantpn** [JPacho/ProyectoIntegrador#11]
leer los valores del sensor de efecto hall

**Comment by JPacho** [comment]
[1784_RPM_Measurement_Techniques_Technical_Note.pdf](https://github.com/JPacho/ProyectoIntegrador/files/3666285/1784_RPM_Measurement_Techniques_Technical_Note.pdf)

Denle una leida al pdf.

Ya logramos detectar la señal del sensor que envia el pulso, ya vimos en el osciloscopio que son 4 pulsos por cada vuelta que da el motor.

En el pdf vienen algunas fórmulas para calcular RPM.

**Comment by JPacho** [comment]
RPM = 60 / (Pulse Period * PPR)

Donde:
PPR = Pulse Per Revolution.
Pulse Period = Duración del Periodo.

**Comment by JPacho** [comment]
De la fórmula anterior la constante 60 se usa sí un pulso equivale a una vuelta del motor.

En nuestro caso como una vuelta equivale a 4 pulsos, la constante que debemos usar es 60/4.

**Comment by JPacho** [comment]
La fórmula utilizada está dando el cálculo correcto de RPM, el problema que se está presentando es la resolución en la variación de RPM, por ejemplo, sólo varia entre 3000 - 2000 -1000. Debe variar de manera más fina. Ej. 3000 - 2600 - 2200 - 1800 - 1400, etc.

**Comment by JPacho** [comment]
Se resolvió el problema de variación de RPM, el issue era debido al tipo de variable que se estaba utilizando.
