### ISSUE TITLE
Lectura del Setpoint

### ISSUE THREAD

**Issue by gibrantpn** [JPacho/ProyectoIntegrador#12]
leer los valores del potenciometro

**Comment by JPacho** [comment]
Debemos determinar cuanto es el valor máximo de RPM al darle el 100% de duty cycle al motor.

Por el momento se está trabajando en obtener la fórmula para RPM.

Ya se están recibiendo los pulsos en el input capture.

**Comment by JPacho** [comment]
Finalmente, se están leyendo de manera correcta los pulsos del sensor y se obtienen los RPM.
