### ISSUE TITLE
Control PID

### ISSUE THREAD

**Issue by gibrantpn** [JPacho/ProyectoIntegrador#13]
implementar el algoritmo de control para el proyecto

**Comment by JPacho** [comment]
Ya empecé a investigar acerca del control PID.
Lo complicado en esta tarea es calcular las constantes de Kp, Ki y Kd.

Este control nos proporcionará una salida que irá al PWM y ésta a su vez al motor, la salida será calculada tomando en base el set point que haya sido establecido.

**Comment by JPacho** [comment]
En este articulo podrán encontrar una explicación muy gráfica y detallada acerca del control PID.
Denle una leída para que vean cual es el objetivo de implementar un control PID.

https://www.luisllamas.es/teoria-de-control-en-arduino-el-controlador-pid/

**Comment by JPacho** [comment]
Método Ziegler-Nichols es el método mas común para encontrar las constantes Kp, Ki y Kd usadas en un control PID. Pueden darle una leida por si gustan entender acerca del PID.

**Comment by JPacho** [comment]
En el Hilo Algoritmo, se agregaron comentarios y algunas variables para implementar la función computePID(), la cual retornará el PWM_output que se conectará al motor.

**Comment by JPacho** [comment]
El control PID funciona de manera adecuada.
