### ISSUE TITLE
Diseño de interfaz

### ISSUE THREAD

**Issue by gibrantpn** [JPacho/ProyectoIntegrador#15]
maquetar el diseño establecido en los requerimientos

**Comment by JPacho** [comment]
Faltan por agregar dos campos que son dimámicos (cambian valor periódicamente)
* set point       (RMP)
* vel de motor (RPM)

Sólo se ha agregado el duty cycle (porcentaje %)

**Comment by JPacho** [comment]
Se agregó funcionalidad en el Hilo Display para desplegar la información del setpoint y la velocidad del motor.

**Comment by JPacho** [comment]
La interfaz ha sido creada de manera correcta.
