### ISSUE TITLE
Implementación de threads

### ISSUE THREAD

**Issue by gibrantpn** [JPacho/ProyectoIntegrador#16]

**Comment by JPacho** [comment]
Se van a crear 3 hilos en ThreadX
* Hilo Lectura
* Hilo Algoritmo
* Hilo Display

**Comment by JPacho** [comment]
El día 05/10/2019 se renombraron los Thread (Hilos) de acuerdo a la arquitectura propuesta.

**Comment by JPacho** [comment]
La creación de Threads (Hilos) ha sido realizada de acuerdo a lo postulado en la arquitectura.
Dado que el inglés es el idioma universal, se nombraron:
* Thread Reading
* Thread Algorithm
* Thread Display
