### ISSUE TITLE
Comunicación entre threads

### ISSUE THREAD

**Issue by gibrantpn** [JPacho/ProyectoIntegrador#17]

**Comment by JPacho** [comment]
* Hilo Lectura provee información a Hilo Algoritmo e Hilo Display.

* Hilo Algoritmo provee información a Hilo Display.

#TODO: Agregar diagrama de comunicación entre hilos.

**Comment by JPacho** [comment]
* Hilo Algortimo provee **duty cycle** al Hilo Display.
* Hilo Lectura provee **set point** y **velocidad motor** al Hilo Display.

**Comment by JPacho** [comment]
La comunicación ha sido implementada conforme a la arquitectura.
