### ISSUE TITLE
Diseño de la Arquitectura

### ISSUE THREAD

**Issue by gibrantpn** [JPacho/ProyectoIntegrador#9]
Seleccionar y diseñar el patrón de diseño para la implementación del proyecto

**Comment by JPacho** [comment]
Debido a que ThreadX ya provee la creación y manejo de threads, propongo dos opciones:

1.- Usar 3 hilos diferentes distribuidos de la siguiente manera:
* Hilo-Lectura, Hilo-Algoritmo, Hilo-Display.

2.- Usar sólo 2 hilos distribuidos de la siguiente manera:
* Hilo-Procesamiento (Lectura y Algoritmo) e Hilo-Display.

En lo personal, creo que la opción 1 es más viable ya que estariamos modularizando cada etapa, así para futuro mantenimiento sería mas sencillo.

**Comment by JPacho** [comment]
Yo creo que debemos darle más prioridad al hardware, por esta razón.
* Hilo de Lectura debe tener la prioridad más alta. (0)
* Hilo de Procesamiento debe tener prioridad media. (1)
* Hilo de display debe tener prioridad más baja. (2)

Con esto aseguramos que la lectura del set point y de los pulsos del sensor siempre ocurrirán dentro del tiempo establecido en los requerimientos.

**Comment by JPacho** [comment]
Antes de saber que Renesas ya incluía ThreadX, estaba pensando en integrar FreeRTOS, o usar un scheduler tipo Round Robin con interrupciones ya que nuestros tres procesos tienen distinta prioridad.

Si todos tuvieran la misma prioridad, corremos el riesgo de no estar leyendo en tiempo real los pulsos del sensor.

**Comment by JPacho** [comment]
Se proponen las siguientes funcionalidades dentro de cada hilo:

**Hilo Lectura**
- Iniciar ADC. *initADC()*
- Leer SetPoint. *getSetPoint()*
- Leer Pulsos. *getPulses()*
- Calcular velocidad de motor. *getMotorSpeed()*

**Hilo Algoritmo**
- Compute PID. *computePID()*
- Obtener duty cycle. *getDutyCycle()*

**Hilo Display**
- Iniciar Display. *initDisplay()*
- Desplegar información. *displayInfo()*

**Comment by JPacho** [comment]
La arquitectura ha sido definida.
